export default[
    {
        path:'/',
        name:'home',
        component:()=>import('@/views/home.vue'),
        children:[
            {
                path:'',
                name:'button',
                component:()=>import('/packages/button/doc/doc.md')
            },
            {
                path:'input',
                name:'input',
                component:()=>import('/packages/input/doc/doc.md')
            },
            {
                path:'textarea',
                name:'textarea',
                component:()=>import('/packages/textarea/doc/doc.md')
            },
            {
                path:'space',
                name:'space',
                component:()=>import('/packages/space/doc/doc.md')
            },
            {
                path:'select',
                name:'select',
                component:()=>import('/packages/select/doc/doc.md')
            },
            {
                path:'radio',
                name:'radio',
                component:()=>import('/packages/radio/doc/doc.md')
            },
            {
                path:'tree',
                name:'tree',
                component:()=>import('/packages/tree/doc/doc.md')
            },
            {
                path:'upload',
                name:'upload',
                component:()=>import('/packages/upload/doc/doc.md')
            },
            {
                path:'dialog',
                name:'dialog',
                component:()=>import('/packages/dialog/doc/doc.md')
            },
            {
                path:'switch',
                name:'switch',
                component:()=>import('/packages/switch/doc/doc.md')
            },
            {
                path:'checkbox',
                name:'checkbox',
                component:()=>import('/packages/checkbox/doc/doc.md')
            },
            {
                path:'message',
                name:'message',
                component:()=>import('/packages/message/doc/doc.md')
            },
            {
                path:'confirm',
                name:'confirm',
                component:()=>import('/packages/confirm/doc/doc.md')
            },
            {
                path:'carousel',
                name:'carousel',
                component:()=>import('/packages/carousel/doc/doc.md')
            },
            {
                path:'pagination',
                name:'pagination',
                component:()=>import('/packages/pagination/doc/doc.md')
            },
            {
                path:'tabs',
                name:'tabs',
                component:()=>import('/packages/tabs/doc/doc.md')
            },
            {
                path:'bread',
                name:'bread',
                component:()=>import('/packages/bread/doc/doc.md')
            },
            {
                path:'skeleton',
                name:'skeleton',
                component:()=>import('/packages/skeleton/doc/doc.md')
            },
            {
                path:'icon',
                name:'icon',
                component:()=>import('/packages/icon/doc/doc.md')
            },
            {
                path:'backtop',
                name:'backtop',
                component:()=>import('/packages/backtop/doc/doc.md')
            },
            {
                path:'drawer',
                name:'drawer',
                component:()=>import('/packages/drawer/doc/doc.md')
            },
            {
                path:'form',
                name:'form',
                component:()=>import('/packages/form/doc/doc.md')
            },
            {
                path:'table',
                name:'table',
                component:()=>import('/packages/table/doc/doc.md')
            }
        ]
    }
]